version: '3'
services:
  api:
    image: registry-api
    build:
      context: .
      dockerfile: ./infra/docker/api/Dockerfile
    tty: true
    env_file:
      - .env
    volumes:
      - ./src:/main/src
      - ./scripts:/main/scripts
      # For local auth with aws, assuming credential file exists
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    expose:
      - "8000"
    ports:
      - 0.0.0.0:8000:8000
    command: "uvicorn app.adapter.into.fastapi.main:app --host 0.0.0.0 --port 8000 --reload --debug"
    depends_on:
      - db
  db:
    build: ./infra/docker/mongo
    restart: always
    volumes:
      - ./infra/docker/mongo/data:/data/db
    env_file:
      - .env
    expose:
      - "27017"
    ports:
      - 0.0.0.0:27017:27017
